name: Yt-Archive-Sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main app
      env:
        ARCHIVE_USERNAME: ${{ secrets.ARCHIVE_USERNAME }}
        ARCHIVE_PASSWORD: ${{ secrets.ARCHIVE_PASSWORD }}
        CHANNELS: ${{ secrets.CHANNELS }}
        MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        JSONBIN_KEY: ${{ secrets.JSONBIN_KEY }}
      run: |
        ia configure --username="$ARCHIVE_USERNAME" --password="$ARCHIVE_PASSWORD"
        python create_collection.py
        python archive_yt_channel.py
